### ISSUE TITLE
Where is the source of DeathPenalty

### ISSUE THREAD

**Issue by Robocraft999** [randombyte-developer/improved-keep-inventory#1]
Hallo,
ich programmiere grade ein SPonge plugin und möchte nach dem TOd ein Effect geben aber bekomme es nicht hin. Der einzige Hinweiß war das Projekt DeathPenalty aber der source-code ist nicht mehr da. Können sie mir da helfen ?

Viele Grüße
Robocraft999

**Comment by randombyte-developer** [comment]
Ich hab dich zum Projekt hinzugefügt, du hast eine Einladung bekommen. Das Plugin ist meine ich noch für sponge 5.X aber soviel hat sich an der API nicht geändert. Das Projekt ist auf privat gestellt und auch nicht auf Sponge Ore, weil mir nach einiger Zeit aufgefallen ist, wie unglücklich der Name ist. Zu der Zeit hatte ich schon nicht mehr Plugin Entwicklung gemacht, und es war einfacher das Plugin zu entfernen als umzubenennen.

**Comment by Robocraft999** [comment]
Vielen Dank
